project_id = "exxrhowfpflufhxdcavo"

[functions.send-document-email]
verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false

[functions.send-stock-alert]
verify_jwt = false

[functions.scheduled-stock-alert]
verify_jwt = false
